name: Deploy Production Version

on:
  push:
    branches: 
      - main

jobs:
  building:
    name: Building react project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building production project
        run: |
          npm install
          npm run build
   
      - name: Publishing on EC2
        run: |

          
          echo "${{ secrets.SSH_PROD_PRIVATE_KEY }}" > ./key.pem
          chmod 400 ./key.pem

          eval $(ssh-agent)
          ssh-add -k ./key.pem

          mkdir -p ~/.ssh && echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config
          
          cd build

          scp -r ./  ubuntu@ec2-15-229-88-93.sa-east-1.compute.amazonaws.com:/var/www/html/